let shopItemsData = [
  {
    id: 1,
    name: "Casual Shirt",
    price: 45,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-1.jpg",
  },
  {
    id: 2,
    name: "Office Shirt",
    price: 100,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-2.jpg",
  },
  {
    id: 3,
    name: "T Shirt",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-3.jpg",
  },
  {
    id: 4,
    name: "Mens Suit",
    price: 300,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-4.jpg",
  },
  {
    id: 5,
    name: "Mens Tie",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-5.png",
  },
  {
    id: 6,
    name: "Casual shoes",
    price: 200,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-6.png",
  },
  {
    id: 7,
    name: "black suit",
    price: 450,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-7.png",
  },
  {
    id: 8,
    name: "polo shirt",
    price: 45,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-8.png",
  },
  {
    id: 9,
    name: "denim shirt",
    price: 85,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-9.png",
  },
  {
    id: 10,
    name: "denim pants",
    price: 120,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-10.png",
  },
  {
    id: 11,
    name: "basic cap",
    price: 35,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-11.png",
  },
  {
    id: 12,
    name: "leather boots",
    price: 350,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: "images/img-12.png",
  },
];
